### ISSUE TITLE
Multiplayer ressources

### ISSUE THREAD

**Issue by Ertuiop333** [TuysuzTavsan/GodotNetworkEnet#1]
Hey! I'm just starting out with multiplayer... are there more beginner friendly examples or ressources? Where did you start out?

Thanks.

**Comment by TuysuzTavsan** [comment]
https://github.com/godotengine/godot-demo-projects/tree/master/networking this might work. 1 year ago when i was starting out webrtc demo helped me out a bit. When you make your first successfull rpc and add players into your scene, you are pretty much done. Copy some of the code and just see it working, after that it is enjoyable.

**Comment by Ertuiop333** [comment]
Thanks! I'll try that out.

**Comment by TuysuzTavsan** [comment]
Alternatively you can check out battlefield.gd on this repo located on DedicatedServer/Src/battlefield.gd. Focus only on authority ids, adding / removing players and connecting multiplayer api signals. Client's battlefield.gd is a little different but not so much from servers. It is different in _ready function which makes sense.
